language: cpp
sudo: require
dist: xenial

os:
 - linux
 - osx
matrix:
 exclude:
# Don't build with clang on Linux
  - os: linux
    compiler: clang
# Don't build with gcc on OSX
  - os: osx
    compiler: gcc

before_install: 
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y;
    sudo apt-get update -qq;
    fi

- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then 
    brew update > /dev/null;
    brew cleanup;
    fi

install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo apt-get -y install build-essential qt5-default qt512tools qt512base qt512quickcontrols2 g++-8 zsync doxygen;
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90;
    fi

- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then 
    brew install doxygen;
    chmod -R 755 /usr/local/opt/qt5/*;
    fi

script: 

- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    source /opt/qt*/bin/qt*-env.sh;
    cmake -DWIDGET_GALLERY=ON -DQML_GALLERY=ON -DDOCS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=ff7tk-continuous-linux CMakeLists.txt;
    make install;
    wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
    chmod a+x linuxdeployqt*.AppImage;
    unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH;
    export VERSION=continuous;
    ./linuxdeployqt*.AppImage ff7tk-continuous-linux/bin/ff7tkWidgetGallery -bundle-non-qt-libs;
    ./linuxdeployqt*.AppImage ff7tk-continuous-linux/bin/ff7tkWidgetGallery -appimage;
    ./linuxdeployqt*.AppImage ff7tk-continuous-linux/bin/ff7tkQmlGallery -bundle-non-qt-libs;
    ./linuxdeployqt*.AppImage ff7tk-continuous-linux/bin/ff7tkQmlGallery -appimage;
    mv COPYING.TXT ff7tk-continuous-linux/;
    tar -zcvf ff7tk-continuous-linux.tar.gz ff7tk-continuous-linux/;
    fi

- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    export QTDIR="/usr/local/opt/qt5";
    export PATH="$QTDIR/bin:$PATH";
    cmake -DWIDGET_GALLERY=ON -DQML_GALLERY=ON -DDOCS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=ff7tk-continuous-macos CMakeLists.txt;
    make install;
    mv COPYING.TXT ff7tk-continuous-macos/;
    macdeployqt ff7tk-continuous-macos/bin/ff7tkWidgetGallery.app;
    macdeployqt ff7tk-continuous-macos/bin/ff7tkQmlGallery.app;
    zip -r -X ff7tk-continuous-macos.zip ff7tk-continuous-macos;
    fi

after_success:
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then bash ./upload.sh ff7tk-continuous-linux.tar.gz; fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then bash ./upload.sh ff7tk-continuous-macos.zip; fi

deploy:
  provider: pages
  local-dir: docs/doc/html
  cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  on:
    condition: ${TRAVIS_OS_NAME} = linux
    branch: master

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:gh-pages)$/
